### ISSUE TITLE
Country/configurable auto-completion

### ISSUE THREAD

**Issue by meme** [malsf21/fair-chair#17]
As an example, when in a GA, a dialog box could show up below the delegate field that shows 3 items (for example) that best fit the currently entered text. This could serve as an aid when entering many countries quickly is needed, i.e.: all the time. Additionally, flag icons could be loaded next to the autocomplete as a visual aid. Another option is allowing the loading of CSVs that contain the delegate name, and an optional image. This could allow pre-configured autocomplete options for crises, or other specialized committees which could use names instead (for example).

**Comment by mattxwang** [comment]
Hm, this is an interesting idea, though I'd have to think about how to implement this. I'll put this on the roadmap for 1.1.0.
