### ISSUE TITLE
Code style standardization

### ISSUE THREAD

**Issue by meme** [malsf21/fair-chair#19]
Just to remove some inconsistencies and make contribution easier-- some possibilities:

- Standard, through https://standardjs.com/#typescript, to remove bikeshedding
- ESLint, through https://www.npmjs.com/package/typescript-eslint-parser, to configure things to your liking (used by standardjs, but already configured), or use a pre-existing configuration
  - https://github.com/airbnb/javascript
  - https://github.com/gajus/eslint-config-canonical

It would also make sense to create an `npm lint` phase that runs on CI to ensure code quality in pull requests.

**Comment by mattxwang** [comment]
Yep, these are all great things to do - when I'm less busy, I'll take a look at improving the quality of the code. Most of this codebase is a mess!
