### ISSUE TITLE
Discord/Gitter/etc. chat to less formally discuss ideas

### ISSUE THREAD

**Issue by meme** [malsf21/fair-chair#21]
I'd like to work on this project a little more, yet some ideas do not warrant a GitHub issue or they are just spitball ideas, so to speak. Perhaps it would be a good idea to have a chat room that allows contributors and users to discuss the software. Some options:

- https://gitter.im/, just log in with your GitHub and make a chat for `fair-chair`
- https://discordapp.com/, create a Discord account and a Discord server (preferred option)
- https://telegram.org/, not everyone has an account for this
- https://slack.com/, it is quite terrible for open-source communities in my opinion, due to the difficulty of having people join

**Comment by mattxwang** [comment]
Hey @meme ,

Just want to say that I appreciate the work you've done so far on this. I'm not entirely sure if this project is big enough yet that we need to have a discord server (though I do love discord), but a Gitter seems like the perfect use case. I've made a Gitter and added the badge to the README - you're welcome to join if you want.
