### ISSUE TITLE
Create testing suite

### ISSUE THREAD

**Issue by meme** [malsf21/fair-chair#26]
(for myself) Explore the options for UI testing in Angular apps

Create a testing suite that is composed of unit tests for internal application logic, then UI tests for the actual Angular front-end. This would be vastly superior to re-running the app every time a feature is being developed (can also be used to triage issues)

**Comment by meme** [comment]
http://www.protractortest.org/

**Comment by meme** [comment]
https://github.com/thymikee/jest-preset-angular

**Comment by mattxwang** [comment]
RIP @meme, it was a good run.

(apparently people still use this? which is surprising?)
